name: Publish npm package
description: A GitHub action publishing an npm package

inputs:
  ref:
    description: >
      Git reference that will be used for package publishing. Used in checkout action.
      When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.
      Otherwise, uses the default branch.
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0"
    default: 16
  registry-url:
    description: >
      Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file,
      and set up auth to read in from env.NODE_AUTH_TOKEN
  scope:
    description: Optional scope for authenticating against scoped registries
  npm-token:
    description: A token for NPM registry authorization
  access:
    description: Tells the registry whether this package should be published as public or restricted.
    default: public
  include-build-step:
    description: Optional flag for running build script before publishing.
    default: false
  dry-run:
    description: A flag for running the command with "--dry-run" option.
    default: false
  directory:
    description: A directory with the package to publish
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref }}
    - uses: ottofeller/npm-run@main
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        directory: ${{ inputs.directory }}
        command: >
          if [[ ${{ inputs.include-build-step }} = true ]];
          then npm run build;
          fi && 
          npm publish --access ${{ inputs.access }} ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
