name: Test the latest-release-commit-hash action

on:
  workflow_dispatch:
    branches: '*'
  pull_request:
    branches: main
    paths: 
      - latest-release-commit-hash/**
      - .github/workflows/test-latest-release-commit-hash.yml
  push:
    paths: 
      - latest-release-commit-hash/**
      - .github/workflows/test-latest-release-commit-hash.yml

jobs:
  test-latest-release-commit-hash:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3 # Need to checkout first to use current repo during testing
      - uses: ./latest-release-commit-hash # ottofeller/github-actions/latest-release-commit-hash@main
        id: commit-hash
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo 'Found release at ${{ steps.commit-hash.outputs.commit_hash }}'
