name: Test the npm-run action

on: 
  workflow_dispatch:
    branches: '*'
  pull_request:
    branches: main
    paths: 
      - npm-run/**
      - .github/workflows/test-npm-run.yml
  push:
    branches: main
    paths: 
      - npm-run/**
      - .github/workflows/test-npm-run.yml
      
jobs:
  test-npm-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 20.x]
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4 # Need to checkout first to use current repo during testing
      - uses: ./npm-run # ottofeller/github-actions/npm-run@main
        with:
          ref: ${{ github.ref }}
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@worldcoin"
          directory: './'
          command: npm list # List package dependencies (fails if node_modules folder missing)
        env:
          CI: true
          NODE_AUTH_TOKEN: SURPRISE
